/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.ss.ttm.utils;

import android.content.BroadcastReceiver;
import android.content.Context;

public class HardWareInfo {
    private BroadcastReceiver batteryReceiver;
    private static int[] mArmArchitecture;
    private static int mCpuType;
}
